environment:
  CONFIGURATION: Release
  TARGET: Default

  NUGET_SERVER_URL: https://www.nuget.org/api/v2/package
  NUGET_API_KEY:
    secure: ZOfa/I/yJnmrPhguM/uqkDDSXlMkHlsX4G2jq1ZtLWlAyIZI435++yrJQsJJ+Fyk

  MYGET_SERVER_URL: https://www.myget.org/F/sharpbrake/api/v2
  MYGET_SYMBOL_SERVER_URL: https://www.myget.org/F/sharpbrake/symbols/api/v2/package
  MYGET_API_KEY:
    secure: /A9mXORoeN6GMmx8yyygIO/r5Jgx91h8Rzw/udcXPzUj/CmBI0Te+nagcL2RGcjR

  CODECOV_TOKEN:
    secure: en+k+6zevr/HyzZacXebARkVoy5Dy0p7pj2LdfYC+eUOveJPoCe6C4LsLbBbaTPY

  # Coverity project token is used for automated build submission
  COVERITY_PROJECT_TOKEN:
    secure: OwB/A40na4tDmHKU8y5LeDl19drugeGF6DXX1cv528s=
  # where email notification on build analysis results will be sent
  COVERITY_NOTIFICATION_EMAIL: sharpbrake@airbrake.io
  
  STRONG_KEY_DECRYPT:
    secure: GDWeVcxc4PEYjnmEnCDfTA==

init:
  - git config --global core.autocrlf true
  
install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt StrongKey.snk.enc -secret $env:STRONG_KEY_DECRYPT

build_script:
  - ps: .\build.ps1 -target $env:TARGET -configuration $env:CONFIGURATION -settings_skipverification=true

# tests are run by build script
test: off

branches:
  only:
    - master

cache:
- tools -> build.cake
